name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read

jobs:
  build-test:
    name: Build and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
      with:
        egress-policy: audit

    - name: Set Environment Variables
      run: |
        echo "TMP=${{ runner.temp }}" >> $GITHUB_ENV

        if [ "${{ github.event_name }}" == "push" ]; then
          echo "BASE_COMMIT=${{ github.event.push.before }}" >> $GITHUB_ENV
          echo "HEAD_COMMIT=${{ github.event.push.after }}" >> $GITHUB_ENV
        fi

        if [ "${{ github.event_name }}" == "pull_request" ]; then
          echo "BASE_COMMIT=${{ github.event.pull_request.base.sha }}" >> $GITHUB_ENV
          echo "HEAD_COMMIT=${{ github.event.pull_request.head.sha }}" >> $GITHUB_ENV
        fi
    - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
    - run: git fetch origin "$BASE_COMMIT" "$HEAD_COMMIT" --depth 1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    - run: yarn --frozen-lockfile
    - run: yarn ci
    - run: bin/compare-git-configs.sh "$BASE_COMMIT" "$HEAD_COMMIT"
